name: Deploy to EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8  # or whichever version you're using
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build Next.js project
      run: pnpm run build
      
    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./"
        target: "/home/${{ secrets.EC2_USER }}/${{ secrets.EC2_PATH }}"
        
    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Node.js if not already installed
          if ! command -v node &> /dev/null
          then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
          fi
          
          # Install pnpm if not already installed
          if ! command -v pnpm &> /dev/null
          then
              curl -fsSL https://get.pnpm.io/install.sh | sh -
              export PNPM_HOME="/home/${{ secrets.EC2_USER }}/.local/share/pnpm"
              export PATH="$PNPM_HOME:$PATH"
              source ~/.bashrc
          fi
          
          # Navigate to project directory
          cd /home/${{ secrets.EC2_USER }}/${{ secrets.EC2_PATH }}
          
          # Install project dependencies and build the project
          pnpm install
          pnpm run build
          
          # Install PM2 if not already installed
          if ! command -v pm2 &> /dev/null
          then
              sudo npm install -g pm2
          fi
          
          # Start/restart the application with PM2
          pm2 restart network_frontend || pm2 start "pnpm start" --name "network_frontend"
